name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yml
  review:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: 'review'
  staging:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: 'staging'
  production:
    needs: [staging]
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: 'production'