name: Deploy / Review

on:
  workflow_call:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: review
    steps:
      - name: Step 1
        run: sleep 30s
        shell: bash
      - name: Step 2
        run: sleep 30s
        shell: bash
      - name: Step 3
        run: sleep 30s
        shell: bash
      - name: Step 4
        run: sleep 30s
        shell: bash
      - name: Step 5
        run: sleep 30s
        shell: bash