name: Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Step 1
        run: sleep 30s
        shell: bash
      - name: Step 2
        run: sleep 30s
        shell: bash
      - name: Step 3
        run: sleep 30s
        shell: bash
      - name: Step 4
        run: sleep 30s
        shell: bash
      - name: Step 5
        run: sleep 30s
        shell: bash